const $ = (selector) => document.querySelector(selector);
const DID_PATTERN = /^did:key:z6Mk[1-9A-HJ-NP-Za-km-z]{44}$/;
const didField = $('#did');
const card = { did: $('#card-did'), name: $('#card-name'), title: $('#card-title'), link: $('#card-link'), avatar: $('#avatar'), lookup: $('#lookup-status'), label: $('#verification-label'), message: $('#verification-message'), meta: $('#record-meta'), verification: $('#verification'), proofAction: $('#proof-action') };
let result = null; let timer = null; let checking = false;
function shortenDid(did) { return did && did.length > 26 ? `${did.slice(0, 15)}…${did.slice(-7)}` : 'did:key:—'; }
function shortenUrl(url) { try { const parsed = new URL(url); return `${parsed.host}${parsed.pathname}`.replace(/\/$/, '') || parsed.host; } catch { return url || 'A recorded contribution link will appear here.'; } }
function formatDate(timestamp) { const date = new Date(timestamp); return Number.isNaN(date.valueOf()) ? '—' : new Intl.DateTimeFormat('en', { month: 'short', day: 'numeric', year: 'numeric' }).format(date).toUpperCase(); }
function setState(state, label, message, meta = '') { card.verification.dataset.state = state; card.label.textContent = label; card.message.textContent = message; card.meta.textContent = meta; }
function updateCard() {
  const did = didField.value.trim(); card.did.textContent = shortenDid(did); card.avatar.textContent = DID_PATTERN.test(did) ? did.slice(-1).toUpperCase() : '?'; card.proofAction.hidden = true;
  if (!did) { card.lookup.textContent = 'PASTE A DID'; card.title.textContent = 'Check your DID'; card.link.textContent = 'A recorded contribution link will appear here.'; setState('idle', 'NOT YET CHECKED', 'Paste a public DID to check for a recorded contribution.'); return; }
  if (!DID_PATTERN.test(did)) { card.lookup.textContent = 'CHECK DID'; card.title.textContent = 'Check your DID'; card.link.textContent = 'Enter a complete public did:key identifier.'; setState('idle', 'NOT YET CHECKED', 'Enter a complete public DID to check for a recorded contribution.'); return; }
  if (checking) { card.lookup.textContent = 'CHECKING…'; card.title.textContent = 'Checking contribution record'; card.link.textContent = 'Searching signed Technocore records.'; setState('checking', 'CHECKING TECHNOCORE', 'Looking for a signed contribution recorded by this DID.'); return; }
  if (result?.did === did && result.verified) { const record = result.record; card.lookup.textContent = 'RECORD FOUND'; card.title.textContent = 'Recorded Technocore Contribution'; card.link.textContent = shortenUrl(record.url); card.proofAction.href = record.url; card.proofAction.hidden = false; setState('verified', 'RECORDED ON TECHNOCORE', 'This DID has a signed public contribution record.', `technocore  ·  #${record.sequence}  ·  ${formatDate(record.recordedAt)}`); return; }
  if (result?.did === did) { card.lookup.textContent = result.lookup || 'NO RECORD FOUND'; card.title.textContent = 'No recorded contribution found'; card.link.textContent = 'No matching signed public contribution is available.'; setState('unverified', 'NO RECORDED CONTRIBUTION FOUND', result.summary || 'No signed public contribution was found for this DID.'); return; }
  card.lookup.textContent = 'READY TO CHECK'; card.title.textContent = 'Check your DID'; card.link.textContent = 'A recorded contribution link will appear here.'; setState('idle', 'NOT YET CHECKED', 'Paste a public DID to check for a recorded contribution.');
}
async function checkDid(did) { checking = true; result = null; updateCard(); try { const response = await fetch(`/api/activity?${new URLSearchParams({ did })}`, { headers: { Accept: 'application/json' } }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); if (didField.value.trim() !== did) return; result = { did, ...payload }; } catch { if (didField.value.trim() !== did) return; result = { did, verified: false, lookup: 'CHECK UNAVAILABLE', summary: 'The contribution check is temporarily unavailable. Please try again.' }; } finally { if (didField.value.trim() === did) { checking = false; updateCard(); } } }
didField.addEventListener('input', () => { clearTimeout(timer); result = null; checking = false; updateCard(); const did = didField.value.trim(); if (DID_PATTERN.test(did)) timer = setTimeout(() => checkDid(did), 450); });
$('#passport-form').addEventListener('submit', (event) => { event.preventDefault(); const did = didField.value.trim(); $('#did-error').textContent = DID_PATTERN.test(did) ? '' : 'Enter a complete public did:key identifier.'; if (DID_PATTERN.test(did)) checkDid(did); });
function passportCanvas() { const canvas = document.createElement('canvas'); canvas.width = 1800; canvas.height = 1160; const ctx = canvas.getContext('2d'); const did = didField.value.trim(); const verified = result?.did === did && result?.verified; const green = '#d9ff4a'; ctx.fillStyle = '#101118'; ctx.fillRect(0, 0, canvas.width, canvas.height); ctx.strokeStyle = 'rgba(255,255,255,.18)'; ctx.lineWidth = 3; ctx.strokeRect(28, 28, 1744, 1104); ctx.fillStyle = '#f7f4ec'; ctx.font = '600 30px ui-monospace, monospace'; ctx.fillText('✦  TECHNOCORE', 95, 122); ctx.fillStyle = '#bebbb5'; ctx.textAlign = 'right'; ctx.font = '24px ui-monospace, monospace'; ctx.fillText('CONTRIBUTION PASSPORT', 1705, 122); ctx.textAlign = 'left'; ctx.fillStyle = green; ctx.beginPath(); ctx.arc(150, 310, 64, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = '#101118'; ctx.textAlign = 'center'; ctx.font = '700 60px Inter, Arial, sans-serif'; ctx.fillText(DID_PATTERN.test(did) ? did.slice(-1).toUpperCase() : '?', 150, 332); ctx.textAlign = 'left'; ctx.fillStyle = '#aaa79f'; ctx.font = '20px ui-monospace, monospace'; ctx.fillText('PUBLIC IDENTITY', 250, 270); ctx.fillStyle = '#f7f4ec'; ctx.font = '700 62px Inter, Arial, sans-serif'; ctx.fillText('Technocore Contributor', 250, 345); ctx.strokeStyle = 'rgba(255,255,255,.25)'; ctx.beginPath(); ctx.moveTo(95, 430); ctx.lineTo(1705, 430); ctx.stroke(); ctx.fillStyle = '#aaa79f'; ctx.font = '20px ui-monospace, monospace'; ctx.fillText('CONTRIBUTION', 95, 500); ctx.fillStyle = '#f7f4ec'; ctx.font = '700 64px Inter, Arial, sans-serif'; ctx.fillText(verified ? 'Recorded Technocore Contribution' : 'Contribution record check', 95, 590); ctx.fillStyle = '#d2cfc7'; ctx.font = '28px ui-monospace, monospace'; ctx.fillText(verified ? shortenUrl(result.record.url) : 'Add a public DID to check.', 95, 675); ctx.strokeStyle = verified ? green : 'rgba(255,255,255,.28)'; ctx.lineWidth = 2; ctx.strokeRect(95, 770, 1610, 120); ctx.fillStyle = verified ? green : '#f7f4ec'; ctx.font = '700 28px ui-monospace, monospace'; ctx.fillText(verified ? '✓  RECORDED ON TECHNOCORE' : '•  NO RECORDED CONTRIBUTION FOUND', 125, 820); ctx.fillStyle = '#aaa79f'; ctx.font = '22px ui-monospace, monospace'; ctx.fillText(verified ? `SIGNED RECORD  ·  /technocore  ·  #${result.record.sequence}  ·  ${formatDate(result.record.recordedAt)}` : 'A signed record is required for verification.', 125, 863); ctx.fillStyle = '#aaa79f'; ctx.font = '20px ui-monospace, monospace'; ctx.fillText('SIGNED DID', 95, 1010); ctx.fillStyle = '#f7f4ec'; ctx.font = '26px ui-monospace, monospace'; ctx.fillText(shortenDid(did), 95, 1055); return canvas; }
$('#download').addEventListener('click', () => { const canvas = passportCanvas(); const link = document.createElement('a'); link.download = 'technocore-contribution-passport.png'; link.href = canvas.toDataURL('image/png'); link.click(); $('#feedback').textContent = 'Downloaded — your contribution passport is ready.'; });
$('#share').addEventListener('click', async () => { const did = didField.value.trim() || 'did:key:…'; const text = result?.verified ? `Recorded Technocore contribution\n${did}\n${result.record.url}` : `Technocore contribution check\n${did}`; try { if (navigator.share) await navigator.share({ title: 'Technocore Contribution Passport', text }); else { await navigator.clipboard.writeText(text); $('#feedback').textContent = 'Share text copied to your clipboard.'; } } catch (error) { if (error.name !== 'AbortError') $('#feedback').textContent = 'Sharing is unavailable in this browser.'; } });
updateCard();
